### PR TITLE
Mobile css

### PR DESCRIPTION
**Pull request by ehne**
Yup it all seems to work on my end, and I am 1 commit ahead of master.
---

* added `.--mobile` and `.--desktop` utility classes to show and hide content depending on breakpoint.
* replaced the roomCode block in the base template with just the code variable, as the room code is not being shown if there isn't a code.
* made header block become block as opposed to flex on mobile breakpoint
* header button group now fills space on mobile breakpoint.
* replaced hiding text by setting font size to zero with just setting display: hidden

### CODE REVIEW

**Comment by Midataur** [comment]
When I last tried it the mathquill input didn't actually work on mobile. Did you fix that?

**Comment by ehne** [comment]
oh, no, I haven't fixed that problem..

what part of it didn't work?

**Comment by Midataur** [comment]
you just couldn't type at all. try it

**Comment by ehne** [comment]
oh thats really whacky, is that more a problem with mathquill?

**Comment by Midataur** [comment]
I reckon so. Desmos worked out how to fix it tho. I think you need to make a custom keyboard

**Pull request merged**
