### PR TITLE
Nicer copying, again

### PR DESCRIPTION
**Pull request by Jmang0**
Same functionality as before but using the clipboard.js library.
- more support
- code is a bit cleaner too

### CODE REVIEW

**Comment by ehne** [comment]
the copying function works well, but did you forget to keep the css? there isn't really an indication that you can copy the text.

**Comment by Jmang0** [comment]
ah oops, i think when i merged master into mine beforehand it disappeared. i'll chuck it back in

**Comment by ehne** [comment]
ye all cool fam

**Comment by Jmang0** [comment]
am I good to merge?

**Comment by ehne** [comment]
uhh just lemme check, I suspect you are, but give me a sec

**Review by ehne — APPROVED** [review]
yup all looks good. it works on my end.

**Comment by Midataur** [comment]
@ehne should I merge it?

**Comment by ehne** [comment]
yeah go ahead

**Pull request merged**
