### PR TITLE
add checking for collisions

### LINKED ISSUE #46: Assign room codes better
This should be pretty self explanatory. We can do a lot better with regards to avoiding collisions with room codes as the current solution is still the hacky one I implemented right at the start.

### PR DESCRIPTION
**Pull request by jmang00**
- I split the `valid_code()` function into two parts.
- When generating a new code, I added a check to see if it already exists.

### CODE REVIEW

**Comment by Midataur** [comment]
2 pieces of feedback

1. Since classrooms is a default dict there is a much better way to do that function. You'll never get an index error, so what you can do is just look at the value of `classrooms[code]` and check its truthiness. Since the default value is `None`, it will evaluate as false if the classroom does not exist and true if the classroom does exist. This could end up looking like this:
```python
def room_exists(code):
    global classrooms
    return bool(classrooms[code])
```
2. Due to the birthday problem the loop will end up running longer on average than it should. I would recommend solving this by just taking the next valid code found by adding 1, regardless of how long it is. This allows for scaling as well as shorter wait times on average.

**Review by Midataur — CHANGES_REQUESTED** [review]
See my comment in the main thread

**Comment by jmang00** [comment]
I get the default dict thing, but I don't quite get what you mean by 2.

When you say adding 1, do you mean adding another digit, or adding 1 to the number? If it's adding 1 to the number, that's pretty much the same as generating a random one. (And probably not ideal because you have adjacent codes).

I think adding a random digit to the end might be the best solution.

**Comment by jmang00** [comment]
How about this?
```
code = random.randint(100000,999999) # generate a random room code
while code_exists(code): 
    code = int(str(code) + str(random.randint(0,9)))
```

**Comment by Midataur** [comment]
I mean literally adding one to the code
Something like this
```python
code = random.randint(100000,999999) # generate a random room code
while code_exists(code): 
    code += 1
```

**Comment by jmang00** [comment]
How would that fix the scaling problem?

If the chance of a collision is high enough to affect runtime (which it'd only be if a significant amount of the 100,000 codes possible were taken), that wouldn't really help.

Also, I don't think the birthday problem actually applies here cos you're adding new items, not comparing every existing item. If generating a random number is the time consuming operation, even with 10,000 existing rooms it'd usually only run once per added code.

**Comment by Midataur** [comment]
The birthday problen definitely applies here, people aren't alll born at
the same time either. I did the math and collisions happen way sooner than
you would think (after single digits thousands I think from memory).

**Comment by Midataur** [comment]
And with regard to scaling if every option was taken it would loop forever

**Comment by jmang00** [comment]
but adding 1 would mean it would check through heaps of the existing codes before reaching a new one.
like say all 1,000,000 codes were taken, and the random number it generated was 233 909. It'd have to individually check most of the codes before picking 1 000 001

**Comment by jmang00** [comment]
The scaling problem is not gonna be an issue unless we have thousands of concurrent rooms.

If you don't wanna worry about that (and would rather have all 6 digit codes), then generating a new random code is the best bet.
Or, if you want it to be scaleable, add another digit on the end.

**Pull request closed without merging**
